# yaml-language-server: $schema=
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-demo-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/achyutamba/ultimate-devops-project-demo.git
    targetRevision: main
    path: helm-charts/otel-demo
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-demo-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
