apiVersion: v1
kind: Secret
metadata:
  name: azdevops-agent-secret
  namespace: azure-pipelines
type: Opaque
stringData:
  AZP_URL: "https://dev.azure.com/achyutaakella/otel-demo"  # Replace with your Azure DevOps org URL
  AZP_TOKEN: "1OXj8y1pkBgm5XHkOgNTCvIaQvlfnMGWHUvD6gPVDkBkHvlnDd02JQQJ99BLACAAAAAAAAAAAAASAZDOceq4"  # Replace with your Personal Access Token
  AZP_POOL: "AKS-Agent-Pool"  # Agent pool name
