apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.fullname" . }}-cartservice
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cartservice
    app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-cartservice
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: otel-demo
spec:
  replicas: {{ .Values.cart.replicaCount | default 1 }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-cartservice
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: cartservice
        app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-cartservice
      {{- if or .Values.global.podAnnotations .Values.cart.podAnnotations }}
      annotations:
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.cart.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "otel-demo" }}
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cartservice
          image: {{ .Values.cart.image.repository }}:{{ .Values.cart.image.tag }}
          imagePullPolicy: {{ .Values.cart.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
              name: service
          {{- $svcSec := .Values.cart.securityContext | default dict }}
          {{- $globalSec := .Values.global.containerSecurityContext | default dict }}
          {{- $sec := $svcSec | default $globalSec }}
          {{- if $sec }}
          securityContext:
            {{- toYaml $sec | nindent 12 }}
          {{- end }}
          {{- $svcRes := .Values.cart.resources | default dict }}
          {{- $globalRes := .Values.global.resources | default dict }}
          {{- $res := $svcRes | default $globalRes }}
          {{- if $res }}
          resources:
            {{- toYaml $res | nindent 12 }}
          {{- end }}
          env:
            # Add environment variables here using .Values.cart.env
            {{- if .Values.cart.env }}
            {{- toYaml .Values.cart.env | nindent 12 }}
            {{- end }}
