apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.fullname" . }}-checkoutservice
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: checkoutservice
    app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-checkoutservice
    app.kubernetes.io/part-of: otel-demo
  {{- if or .Values.global.podAnnotations .Values.checkout.podAnnotations }}
  annotations:
    {{- with .Values.global.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.checkout.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.checkout.replicaCount | default 1 }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-checkoutservice
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: checkoutservice
        app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-checkoutservice
      {{- if or .Values.global.podAnnotations .Values.checkout.podAnnotations }}
      annotations:
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.checkout.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "otel-demo" }}
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: checkoutservice
          image: {{ .Values.checkout.image.repository }}:{{ .Values.checkout.image.tag }}
          imagePullPolicy: {{ .Values.checkout.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
              name: service
          {{- $svcSec := .Values.checkout.securityContext | default dict }}
          {{- $globalSec := .Values.global.containerSecurityContext | default dict }}
          {{- $sec := $svcSec | default $globalSec }}
          {{- if $sec }}
          securityContext:
            {{- toYaml $sec | nindent 12 }}
          {{- end }}
          {{- $svcRes := .Values.checkout.resources | default dict }}
          {{- $globalRes := .Values.global.resources | default dict }}
          {{- $res := $svcRes | default $globalRes }}
          {{- if $res }}
          resources:
            {{- toYaml $res | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.checkout.env }}
            {{- toYaml .Values.checkout.env | nindent 12 }}
            {{- end }}
