apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.fullname" . }}-frauddetectionservice
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frauddetectionservice
    app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-frauddetectionservice
spec:
  replicas: {{ .Values.frauddetection.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-frauddetectionservice
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: frauddetectionservice
        app.kubernetes.io/name: {{ include "otel-demo.fullname" . }}-frauddetectionservice
      {{- if or .Values.global.podAnnotations .Values.frauddetection.podAnnotations }}
      annotations:
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.frauddetection.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "otel-demo" }}
      {{- with .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-kafka
          image: busybox:latest
          command: ["sh","-c","until nc -z -v -w30 {{ include \"otel-demo.fullname\" . }}-kafka 9092; do echo waiting for kafka; sleep 2; done;"]
      containers:
        - name: frauddetectionservice
          image: {{ .Values.frauddetection.image.repository }}:{{ .Values.frauddetection.image.tag }}
          imagePullPolicy: {{ .Values.frauddetection.image.pullPolicy | default "IfNotPresent" }}
          {{- $svcSec := .Values.frauddetection.securityContext | default dict }}
          {{- $globalSec := .Values.global.containerSecurityContext | default dict }}
          {{- $sec := $svcSec | default $globalSec }}
          {{- if $sec }}
          securityContext:
            {{- toYaml $sec | nindent 12 }}
          {{- end }}
          {{- $svcRes := .Values.frauddetection.resources | default dict }}
          {{- $globalRes := .Values.global.resources | default dict }}
          {{- $res := $svcRes | default $globalRes }}
          {{- if $res }}
          resources:
            {{- toYaml $res | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.frauddetection.env }}
            {{- toYaml .Values.frauddetection.env | nindent 12 }}
            {{- end }}