{{- if .Values.frontendproxy.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "otel-demo.fullname" . }}-frontendproxy
  annotations:
    {{- with .Values.frontendproxy.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.frontendproxy.ingress.className }}
  ingressClassName: {{ .Values.frontendproxy.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.frontendproxy.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "otel-demo.fullname" $ }}-frontendproxy
                port:
                  number: {{ $.Values.frontendproxy.service.port | default 8080 }}
          {{- end }}
    {{- end }}
{{- end }}